### ISSUE TITLE
Some links are broken

### ISSUE THREAD

**Issue by xiangchen96** [MBCProject/mbc-stix2.1#1]
- https://github.com/MBCProject/mbc-markdown/blob/main/anti-static-analysis/obfuscated-files-or-information.md
- https://github.com/MBCProject/mbc-markdown/blob/main/persistence/registry-run-keys-/-startup-folder.md

**Comment by dzbeck** [comment]
@xiangchen96 thanks so much for letting us know. We'll try to fix things soon.

**Comment by dzbeck** [comment]
@xiangchen96 Hopefully, the broken links have been fixed with the latest updates. Please let us know if you find any other issues. Thanks very much for your help!
