### ISSUE TITLE
Can't find corresponding behavior via behavior_ref

### ISSUE THREAD

**Issue by xiangchen96** [MBCProject/mbc-stix2.1#2]
Example:

https://github.com/MBCProject/mbc-stix2.1/blob/e29510fe6f4085d1417e3144f7646aacdc29f4db/mbc/malware-method/malware-method--895ed219-4767-41c2-80f5-5958f7faf5be.json#L18

`B0007` looks like it is actually `malware-behavior--54b3edd9-186c-4b8e-858e-95318349f658`

**Comment by dzbeck** [comment]
@xiangchen96 Thanks so much for bringing this to our attention. We are working on a fix and we hope to have an update available soon.

**Comment by dzbeck** [comment]
Hi @xiangchen96 Sorry for the long delay. Please see [v24.09](https://github.com/MBCProject/mbc-stix2.1/releases/tag/v24.09) for a corrected STIX 2.1 representation. Thanks again for your help.
